# Generated by Django 4.2.2 on 2023-07-28 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=20)),
                ('cvv', models.PositiveSmallIntegerField()),
                ('issue', models.CharField(max_length=10)),
                ('expiration', models.CharField(max_length=10)),
                ('balance', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('title', models.CharField(blank=True, default='new', max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
