# Generated by Django 4.2.2 on 2023-07-05 12:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=20)),
                ('cvv', models.PositiveSmallIntegerField()),
                ('issue', models.CharField(max_length=10)),
                ('expiration', models.CharField(max_length=10)),
                ('balance', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
